#ifndef NETWORK_SPEC_H
#define NETWORK_SPEC_H

static const char *embedded_cli_spec =
"# Network Configuration CLI Specification\n"
"# This file defines the CLI syntax using CLIgen format\n"
"#\n"
"# Cisco-style modes: two named trees are defined below.\n"
"#   'base'   - operational mode,  prompt 'network> '\n"
"#   'config' - configuration mode, prompt 'network(config)> '\n"
"# The 'mode' callback switches the active tree and the prompt.\n"
"\n"
"prompt = \"network> \";\n"
"comment = \"#\";\n"
"\n"
"# ===== Operational mode (default/active tree) =====\n"
"treename = \"base\";\n"
"\n"
"# Show available interfaces dynamically\n"
"show(\"Show network configuration\") {\n"
"    interfaces(\"Show all interfaces\"), show_interfaces();\n"
"    interface <ifname:string interface()>(\"Interface name\"), show_interface();\n"
"}\n"
"\n"
"# Enter configuration mode\n"
"config(\"Enter configuration mode\"), mode(\"config\", \"network(config)> \");\n"
"\n"
"help(\"Show help\"), help_cmd();\n"
"quit(\"Quit the CLI\"), quit_cmd();\n"
"\n"
"# ===== Configuration mode =====\n"
"treename = \"config\";\n"
"\n"
"history(\"Change command history size\") {\n"
"    <size:uint16 range[3:100]>(\"history size\"), set_history_size();\n"
"}\n"
"# Configure interface settings\n"
"interface <ifname:string interface()>(\"Interface name\") {\n"
"    ip <ipaddr:ipv4addr>(\"IP address\"), set_interface_ip();\n"
"    no ip(\"remove IP address\"), remove_interface_ip();\n"
"    ipv6 <ipaddr:ipv6addr>(\"IPv6 address\"), set_interface_ipv6();\n"
"    no ipv6(\"remove IPv6 address\"), remove_interface_ipv6();\n"
"    mtu <size:uint16 range[68:65535]>(\"MTU size\"), set_mtu();\n"
"}\n"
"\n"
"# Show is also available inside config mode\n"
"show(\"Show network configuration\") {\n"
"    interfaces(\"Show all interfaces\"), show_interfaces();\n"
"    interface <ifname:string interface()>(\"Interface name\"), show_interface();\n"
"    history (\"Show history\"), show_history();\n"
"}\n"
"\n"
"# Leave configuration mode, back to operational mode\n"
"exit(\"Exit configuration mode\"), mode(\"base\", \"network> \");\n"
"end(\"Exit configuration mode\"), mode(\"base\", \"network> \");\n"
"\n"
"help(\"Show help\"), help_cmd();\n"
"quit(\"Quit the CLI\"), quit_cmd();\n";

#endif
