CC = gcc
CFLAGS = -Wall -g -I/usr/include/cligen
LDFLAGS = -lcligen

TARGET = ifconfig_cli
SOURCES = ifconfig_cli.c
OBJECTS = $(SOURCES:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)

run: $(TARGET)
	./$(TARGET)

.PHONY: all clean run
